services:
  - type: web
    name: near-mainnet-postgrest
    plan: starter
    env: docker
    dockerfilePath: ./postgrest/Dockerfile
    envVars:
      - key: PGRST_DB_URI
        value: postgres://public_readonly:nearprotocol@104.199.89.51/mainnet_explorer
      - key: PGRST_DB_SCHEMA
        value: public
      - key: PGRST_DB_ANON_ROLE
        value: public_readonly
  - type: web
    name: near-mainnet-swagger
    plan: starter
    env: docker
    dockerfilePath: ./swagger/Dockerfile
    envVars:
      - key: API_URL
        value: https://near-mainnet-postgrest.onrender.com
