services:
  - type: web
    name: near-testnet-postgrest
    plan: starter
    env: docker
    dockerfilePath: ./postgrest/Dockerfile
    envVars:
      - key: PGRST_DB_URI
        value: postgres://public_readonly:nearprotocol@35.184.214.98/testnet_explorer
      - key: PGRST_DB_SCHEMA
        value: public
      - key: PGRST_DB_ANON_ROLE
        value: public_readonly
